//LISTA DE ACCIONES QUE HAREMOS PARA MANIPULA NUESTRO ESTADO GLOBAL

export const
    // SOLICITUDES    
    GET_ALL_DOG_BREEDS = "GET_ALL_DOG_BREEDS",
    GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS",

    // FILTROS
    FILTER_DOG_BREEDS = "FILTER_DOG_BREEDS",
    ORDER_DOG_BREEDS = "ORDER_DOG_BREEDS",
    RESET_FILTER = "RESET_FILTER",

    //EVENTOS
    NOT_SUCCESFUL_RESPONSE = "NOT_SUCCESFUL_RESPONSE"


